// <auto-generated />
using System;
using KodeFlow.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KodeFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspecialidadeVeterinario", b =>
                {
                    b.Property<int>("EspecialidadesEspecialidadeId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinariosVeterinarioId")
                        .HasColumnType("int");

                    b.HasKey("EspecialidadesEspecialidadeId", "VeterinariosVeterinarioId");

                    b.HasIndex("VeterinariosVeterinarioId");

                    b.ToTable("EspecialidadeVeterinario");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Animal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_Cor");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ds_Nome");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vl_Peso");

                    b.Property<int>("RacaId")
                        .HasColumnType("int")
                        .HasColumnName("id_Raca");

                    b.Property<int>("Sexo")
                        .HasColumnType("int")
                        .HasColumnName("tp_Sexo");

                    b.Property<int>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("id_Tutor");

                    b.HasKey("AnimalId");

                    b.HasIndex("RacaId");

                    b.HasIndex("TutorId");

                    b.ToTable("tbl_Animais");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Consulta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("id_Animal");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_Consulta");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_Fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_Inicio");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tp_Status");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_Veterinario");

                    b.HasKey("ConsultaId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("tbl_Consultas");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Contato", b =>
                {
                    b.Property<int>("ContatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Contato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContatoId"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nr_Celular");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ds_Email");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nr_Telefone");

                    b.Property<int>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("id_Tutor");

                    b.HasKey("ContatoId");

                    b.HasIndex("TutorId")
                        .IsUnique();

                    b.ToTable("tbl_Contatos");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Endereco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnderecoId"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("char(9)")
                        .HasColumnName("ds_Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_Cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ds_Complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("ds_Estado");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ds_Numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ds_Rua");

                    b.Property<int>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("id_Tutor");

                    b.HasKey("EnderecoId");

                    b.HasIndex("TutorId")
                        .IsUnique();

                    b.ToTable("tbl_Enderecos");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Especialidade", b =>
                {
                    b.Property<int>("EspecialidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Especialidade");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadeId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ds_Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ds_Nome");

                    b.HasKey("EspecialidadeId");

                    b.ToTable("tbl_Especialidades");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Especie", b =>
                {
                    b.Property<int>("EspecieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Especie");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecieId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ds_Nome");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ds_NomeCientifico");

                    b.HasKey("EspecieId");

                    b.ToTable("tbl_Especies");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Prontuario", b =>
                {
                    b.Property<int>("ProntuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Prontuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProntuarioId"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int")
                        .HasColumnName("id_Consulta");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_Inicio");

                    b.Property<string>("DescricaoClinica")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ds_DescricaoClinica");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ds_Diagnostico");

                    b.HasKey("ProntuarioId");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("tbl_Prontuarios");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Raca", b =>
                {
                    b.Property<int>("RacaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Raca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacaId"));

                    b.Property<int>("EspecieId")
                        .HasColumnType("int")
                        .HasColumnName("id_Especie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ds_Nome");

                    b.HasKey("RacaId");

                    b.HasIndex("EspecieId");

                    b.ToTable("tbl_Racas");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Tutor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("ds_CPF");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ds_Nome");

                    b.HasKey("TutorId");

                    b.ToTable("tbl_Tutores");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Veterinario", b =>
                {
                    b.Property<int>("VeterinarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Veterinario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeterinarioId"));

                    b.Property<string>("CRMV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nr_Crmv");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ds_Nome");

                    b.HasKey("VeterinarioId");

                    b.ToTable("tbl_Veterinarios");
                });

            modelBuilder.Entity("EspecialidadeVeterinario", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Especialidade", null)
                        .WithMany()
                        .HasForeignKey("EspecialidadesEspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodeFlow.Models.Entities.Veterinario", null)
                        .WithMany()
                        .HasForeignKey("VeterinariosVeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Animal", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Raca", "Raca")
                        .WithMany("Animais")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodeFlow.Models.Entities.Tutor", "Tutor")
                        .WithMany("Animais")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raca");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Consulta", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Animal", "Animal")
                        .WithMany("Consultas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodeFlow.Models.Entities.Veterinario", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Contato", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Tutor", "Tutor")
                        .WithOne("Contato")
                        .HasForeignKey("KodeFlow.Models.Entities.Contato", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Endereco", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Tutor", "Tutor")
                        .WithOne("Endereco")
                        .HasForeignKey("KodeFlow.Models.Entities.Endereco", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Prontuario", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Consulta", "Consulta")
                        .WithOne("Prontuario")
                        .HasForeignKey("KodeFlow.Models.Entities.Prontuario", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Raca", b =>
                {
                    b.HasOne("KodeFlow.Models.Entities.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Animal", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Consulta", b =>
                {
                    b.Navigation("Prontuario")
                        .IsRequired();
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Especie", b =>
                {
                    b.Navigation("Racas");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Raca", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Tutor", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Contato")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("KodeFlow.Models.Entities.Veterinario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
